version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/ree-balance
      - NODE_ENV=development
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./api:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - app-network

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - REACT_APP_API_URL=http://localhost:4000/graphql
    volumes:
      - ./web:/app
      - /app/node_modules
    depends_on:
      - api
    restart: unless-stopped
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=ree-balance
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
